# This file is based on examples in
# https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

# Note that all the "sudo" commands here appear to cause a warning message
# "sudo: setrlimit(RLIMIT_CORE): operation not permitted"
# This appears to be a known harmless annoyance:
# https://gitlab.alpinelinux.org/alpine/aports/-/issues/11122

name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.11]

    steps:
    - uses: actions/checkout@v3

    - name: pwd
      run: pwd

    - name: ls
      run: ls

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: which pip after python setup
      run: |
        python -m pip install --upgrade pip
        pip --version

    - name: pwd
      run: pwd

    - name: ls
      run: ls

    - name: Install python dependencies
      run: |
        pip install -r requirements.txt

    - name: Install package
      run: pip install -v .

    - name: Run tests
      run: python -m unittest

